### PR TITLE
Update References

### LINKED ISSUE #1: Fix References
- ISO Directives mentioned in scope, add to Bibliography
- SMPTE ST 2094-2 mentioned in "Defining individual ULs", add to Bibliography
- SMPTE ST 382-4 mentioned in "Defining individual ULs", add to Bibliography
- SMPTE ST 377-1 mentioned in various sections, add to Bibliography
- ISO/IEC 13818-7, ISO/IEC 14496-3, ISO/IEC 14496-3:2009/Amd 4 mentioned in "Defining groups and sets', add to Bibliography
- SMPTE AG-03 not used in doc, remove from Normative References, or add to doc as reference
- SMPTE AG-04* not used in doc, remove from Normative References, or add to doc as reference
- SMPTE AG-18 not used in doc, remove from Normative References, or add to doc as reference
- SMPTE ST 2029:2009 not used in doc, remove from Normative References, or add to doc as reference
- SMPTE ST 336:2017 not used in doc, remove from Normative References

### PR DESCRIPTION
**Pull request by SteveLLamb**
Pass on updating references, closes #1

### CODE REVIEW

**Review by palemieux — CHANGES_REQUESTED** [review]
Shouldn't we un-date all references?

**Comment by SteveLLamb** [comment]
> Shouldn't we un-date all references?

Addressed in https://github.com/SMPTE/ag-24/pull/3/commits/7327c05f6c4505381db2d883302cfc14c28b5bc9

**Review by palemieux — APPROVED** [review]

**Comment by SteveLLamb** [comment]
Notice to be sent to ST - this PR is under 2-week review, and will be merged on 2023-04-10 if no objections.

**Comment by SteveLLamb** [comment]
Merging as per above, no objections from ST.

**Pull request merged**
